function expr = comp(t,in2,in3)
%COMP
%    EXPR = COMP(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    14-May-2022 22:01:01

param31 = in3(:,1);
param32 = in3(:,2);
param33 = in3(:,3);
param34 = in3(:,4);
param35 = in3(:,5);
x1 = in2(1,:);
x2 = in2(2,:);
x3 = in2(3,:);
t2 = param33.*x1;
t3 = param34.*x2;
t4 = param35.*x1;
t5 = param31.*x1.*x2;
t6 = param31.*x1.*x3;
t7 = param32.*x2.*x3;
expr = [-t2-t4+t5+t6;-t3-t5+t7;t2+t3+t4-t6-t7];
